Update Jenkinsfile2

diff --git a/Jenkinsfile2 b/Jenkinsfile2
--- a/Jenkinsfile2
+++ b/Jenkinsfile2
@@ -3,8 +3,9 @@ pipeline {
     stages {
         stage('Test') {
             steps {
-                 echo 'Fail!'; exit 1
                  currentBuild.result = 'UNSTABLE'
+                 echo 'Fail!'; exit 1
+                 
             }
         }
     }
