Update Jenkinsfile2

diff --git a/Jenkinsfile2 b/Jenkinsfile2
--- a/Jenkinsfile2
+++ b/Jenkinsfile2
@@ -1,20 +1,36 @@
-
-
 pipeline {
     agent any
     stages {
-        stage('Build') {
+        stage('Test') {
             steps {
-                sh 'echo "Hello World"'
-                sh '''
-                    echo "Multiline shell steps works too"
-                    #ls -lah
-                    echo "doing echo again"
-                '''
+                 echo 'Fail!'; exit 1
             }
         }
     }
+    post {
+        always {
+            echo 'This will always run'
+        }
+        success {
+            echo 'This will run only if successful'
+
+	    //archiveArtifacts artifacts: '*.war'
+        }
+        failure {
+            echo 'This will run only if failed'
+
+	    //mail bcc: '', body: 'Please look into issue at priority and fix it', cc: '', from: '', replyTo: '', subject: 'This build failed', to: 'devopsteam@abc.com'
+        }
+        unstable {
+            echo 'This will run only if the run was marked as unstable'
+        }
+        changed {
+            echo 'This will run only if the state of the Pipeline has changed'
+            echo 'For example, if the Pipeline was previously failing but is now successful'
+        }
+    }
 }
- 
+
+
 
 
