Update Jenkinsfile2

diff --git a/Jenkinsfile2 b/Jenkinsfile2
--- a/Jenkinsfile2
+++ b/Jenkinsfile2
@@ -4,7 +4,8 @@ pipeline {
         stage('Test') {
             steps {
                  
-                 echo 'Fail!'; exit 1
+                 echo 'Fail!'
+                 sh 'exit 1'
                  
             }
         }
