Update Jenkinsfile2

diff --git a/Jenkinsfile2 b/Jenkinsfile2
--- a/Jenkinsfile2
+++ b/Jenkinsfile2
@@ -1,33 +1,29 @@
 pipeline {
-	    agent any
-	    parameters {
-	        choice(
-	            choices: ['greeting' , 'silence'],
-	            description: '',
-	            name: 'REQUESTED_ACTION')
-	    }
-	    
-	    stages {
-	        stage ('Speak') {
-	            when {
-	                // Only say hello if a "greeting" is requested
-	                expression { params.REQUESTED_ACTION == 'greeting' }
-	            }
-	            steps {
-	                                
-	                echo "Hello, bitwiseman!"
-	            }
-	        }
-	        
-	        stage ('Silent') {
-	            when {
-	                // Only say hello if a "greeting" is requested
-	                expression { params.REQUESTED_ACTION == 'silence' }
-	            }
-	            steps {
-	                                
-	                echo "Hello, Silent stage executed!"
-	            }
-	        } 
-	    }
-	}
+    agent any
+    stages {
+        stage('Test') {
+            steps {
+                 echo 'Fail!'; exit 1
+            }
+        }
+    }
+    
+	post {
+        always {
+            echo 'This will always run'
+        }
+        success {
+            echo 'This will run only if successful'
+        }
+        failure {
+            echo 'This will run only if failed'
+        }
+        unstable {
+            echo 'This will run only if the run was marked as unstable'
+        }
+        changed {
+            echo 'This will run only if the state of the Pipeline has changed'
+            echo 'For example, if the Pipeline was previously failing but is now successful'
+        }
+    }
+}
